api/urls.py
from django.urls import path
from .views import todos_view, test_spotify

app_name = "api"
urlpatterns = [
    path('todos/', todos_view, name='todos'),
    path('spotify/', test_spotify, name='spotify')
]

corsi_formazione/urls.py
from django.urls import path
from .views import index, lista_corsi, lista_dettagli, dettagli_corso, view_a, view_c, view_d, view_e, view_f

app_name = "corsi_formazione"

urlpatterns = [
    path('', index, name='index'),
    path('lista_corsi', lista_corsi, name='lista_corsi'),
    path('lista_dettagli', lista_dettagli, name='lista_dettagli'),
    path('lista_dettagli/<int:pk>', dettagli_corso, name='dettagli_corso'), #view_b
    path('view_a', view_a, name='view_a'),
    path('view_c', view_c, name='view_c'),
    path('view_d', view_d, name='view_d'),
    path('view_e', view_e, name='view_e'),
    path('statistiche', view_f, name='statistiche'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root


app_name="primo_progetto"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('eventi/',include("eventi.urls",namespace="eventi")),
    path('rubrica/',include("rubrica.urls",namespace="rubrica")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('', index_root, name='index_root'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('api/',include("api.urls",namespace="api")),
    path('products/',include("products.urls",namespace="products")),
]

corsi_formazione/models.py
from django.db import models

class Corso(models.Model):
    titolo = models.CharField(max_length=40)
    descrizione = models.TextField(max_length=100)
    data_inizio = models.DateField()
    data_fine = models.DateField()
    posti_disponibili = models.IntegerField(default=0,blank=True)
    
    def __str__(self):
        return self.titolo
 
    class Meta:
        verbose_name = "Corso"
        verbose_name_plural = "Corsi"

corsi_formazione/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from .models import Corso

def index(request):
    return render(request, "index_corsi.html")

def lista_corsi(request):
    corsi = Corso.objects.all()

    context = {
                "corsi": corsi,
            }
    return render(request, "lista_corsi.html", context)

def lista_dettagli(request):
    corsi = Corso.objects.all()

    context = {
                "corsi": corsi,
            }
    return render(request, "lista_dettagli.html", context)

def dettagli_corso(request, pk): #view_b
    corso = get_object_or_404(Corso, pk=pk)
    context = {
                "corso": corso,
            }
    return render(request, "dettagli_corso.html", context)

def view_a(request):
    #elenco ordinato per data dei corsi
    corsi_ordinati = Corso.objects.order_by('data_inizio')
    context = {
                "corsi_ordinati": corsi_ordinati,
            }
    return render(request, "c_view_a.html", context)

#view_b fatta precedentemente con il nome dettagli_corso

def view_c(request):
    #corsi che iniziano dopo il 01/05/2025
    corsi_data = Corso.objects.filter(data_inizio__gt=datetime.date(2025,5,1))
    context = {
                "corsi_data": corsi_data,
            }
    return render(request, "c_view_c.html", context)

def view_d(request):
    #corsi con meno o uguale di 20 posti disponibili
    corsi_con_meno_20p = Corso.objects.filter(posti_disponibili__lte=20)
    context = {
                "corsi_con_meno_20p": corsi_con_meno_20p,
            }
    return render(request, "c_view_d.html", context)

def view_e(request):
    #corsi che terminano il 30/04/2025
    corsi_terminanti_giorno = Corso.objects.filter(data_fine=datetime.date(2025,4,30))
    context = {
                "corsi_terminanti_giorno": corsi_terminanti_giorno,
            }
    return render(request, "c_view_e.html", context)

def view_f(request):
    #statistiche avanzate
    corso_posti_maggiori = Corso.objects.order_by('-posti_disponibili').first()
    corso_posti_minori = Corso.objects.order_by('posti_disponibili').first()
    
    totale_posti=0
    corsi = Corso.objects.all()
    for corso in corsi:
        totale_posti+=corso.posti_disponibili

    context = {
                "corso_posti_maggiori": corso_posti_maggiori,
                "corso_posti_minori": corso_posti_minori,
                "totale_posti": totale_posti,
            }
    return render(request, "statistiche.html", context)

corsi_formazione/templates/c_view_a.html
{% extends "base.html"%}
{%block title%} {{block.super}} | View a {%endblock title%}

{%block content%}
    <h3>Corsi ordinati per data di inizio:</h3>
    <br>
    <ul>
        {% for corso in corsi_ordinati %}
            <li><a href="{% url 'corsi_formazione:dettagli_corso' corso.id %}">{{corso.titolo}}</a> - {{corso.data_inizio}}</li>
        {% endfor %}
    </ul>
{%endblock content%}

corsi_formazione/templates/c_view_c.html
{% extends "base.html"%}
{%block title%} {{block.super}} | View c {%endblock title%}

{%block content%}
    <h3>Corsi che iniziano dopo il 01/05/2025</h3>
    <br>
    <ul>
        {% for corso in corsi_data %}
            <li><a href="{% url 'corsi_formazione:dettagli_corso' corso.id %}">{{corso.titolo}}</a> - {{corso.data_inizio}}</li>
        {% endfor %}
    </ul>
{%endblock content%}

corsi_formazione/templates/c_view_d.html
{% extends "base.html"%}
{%block title%} {{block.super}} | View d {%endblock title%}

{%block content%}
    <h3>Corsi con meno di 20 posti disponibili</h3>
    <br>
    <ul>
        {% for corso in corsi_con_meno_20p %}
            <li><a href="{% url 'corsi_formazione:dettagli_corso' corso.id %}">{{corso.titolo}}</a> - {{corso.posti_disponibili}} posti disponibili</li>
        {% endfor %}
    </ul>
{%endblock content%}

corsi_formazione/templates/c_view_e.html
{% extends "base.html"%}
{%block title%} {{block.super}} | View e {%endblock title%}

{%block content%}
    <h3>Corsi terminanti il 30/04/2025</h3>
    <br>
    <ul>
        {% for corso in corsi_terminanti_giorno %}
            <li><a href="{% url 'corsi_formazione:dettagli_corso' corso.id %}">{{corso.titolo}}</a> - finisce il {{corso.data_fine}}</li>
        {% endfor %}
    </ul>
{%endblock content%}

corsi_formazione/templates/dettagli_corso.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Dettagli {{corso.titolo}} {%endblock title%}

 {%block content%}
    <h1>{{corso.titolo}}</h1>
    <p>{{corso.descrizione}}</p>
    <br>
    <p>
        <b>Data inizio: </b>{{corso.data_inizio}}<br>
        <b>Data fine: </b>{{corso.data_fine}}<br>
        <br>
        <i>Posti disponibili: {{corso.posti_disponibili}}</i>
    </p>
 {%endblock content%}

corsi_formazione/templates/index_corsi.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Index corsi {%endblock title%}

 {%block content%}
    <h1>Benvenuto nel sistema di gestione dei Corsi di Formazione</h1>
    <br>
    <h4>Indice:</h4>
    <ul>
        <li><a href="/">index root</a></li>
        <li><a href="{% url 'corsi_formazione:lista_corsi'%}">Lista dei corsi</a></li>
        <li><a href="{% url 'corsi_formazione:lista_dettagli'%}">Lista dettagli dei corsi</a></li>
        <li><a href="{% url 'corsi_formazione:view_a'%}">Elenco di corsi ordinato per data di inizio</a></li>
        <li><a href="{% url 'corsi_formazione:view_c'%}">Corsi che iniziano dopo il 01/05/2025</a></li>
        <li><a href="{% url 'corsi_formazione:view_d'%}">Corsi con meno di 20 posti disponibili</a></li>
        <li><a href="{% url 'corsi_formazione:view_e'%}">Corsi che terminano entro il 30/04/2025</a></li>
        <li><a href="{% url 'corsi_formazione:statistiche'%}">Statistiche sui corsi</a></li>
    </ul>
 {%endblock content%}

 <!--<li><a href="{% url 'corsi_formazione:'%}"></a></li>-->

corsi_formazione/templates/lista_corsi.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Lista corsi {%endblock title%}

 {%block content%}
    <h2>Lista dei corsi</h2>
    <br>
    <ul>
        {% for corso in corsi %}
            <li><a href="{% url 'corsi_formazione:dettagli_corso' corso.id %}">{{corso.titolo}}</a></li>
        {% endfor %}
    </ul>
 {%endblock content%}

corsi_formazione/templates/lista_dettagli.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Lista corsi {%endblock title%}

 {%block content%}
    <h2>Lista dettagli dei corsi</h2>
    <br>
    {% for corso in corsi %}
        <hr>
        <h5><a href="{% url 'corsi_formazione:dettagli_corso' corso.id %}">{{corso.titolo}}</a></h5>
        <br>
        <p>
            <b>Data inizio: </b>{{corso.data_inizio}}<br>
            <b>Data fine: </b>{{corso.data_fine}}<br>
            <br>
            <i>Posti disponibili: {{corso.posti_disponibili}}</i>
        </p>
        <hr>
    {% endfor %}
 {%endblock content%}

corsi_formazione/templates/statistiche.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Statistiche avanzate {%endblock title%}

{%block content%}
    <h2>Statistiche avanzate sui corsi</h2>
    <br>
    <ul>
        <li>Corso con più posti disponibili: <a href="{% url 'corsi_formazione:dettagli_corso' corso_posti_maggiori.id %}">{{corso_posti_maggiori.titolo}}</a> con {{corso_posti_maggiori.posti_disponibili}} posti disponibili</li>
        <li>Corso con meno posti disponibili: <a href="{% url 'corsi_formazione:dettagli_corso' corso_posti_minori.id %}">{{corso_posti_minori.titolo}}</a> con {{corso_posti_minori.posti_disponibili}} posti disponibili</li>
        <br>
        <li>Totale posti disponibili: {{totale_posti}}</li>
    </ul>
{%endblock content%}