api/urls.py
from django.urls import path
from .views import todos_view, test_spotify

app_name = "api"
urlpatterns = [
    path('todos/', todos_view, name='todos'),
    path('spotify/', test_spotify, name='spotify')
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, welcome, lista, chi_siamo, variabili, index

app_name = "prima_app"
urlpatterns = [
    path('', index, name='index'),
    path('home', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chi_siamo', chi_siamo, name='chi_siamo'),
    path('variabili', variabili, name='variabili'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root


app_name="primo_progetto"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('eventi/',include("eventi.urls",namespace="eventi")),
    path('rubrica/',include("rubrica.urls",namespace="rubrica")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('', index_root, name='index_root'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('api/',include("api.urls",namespace="api")),
    path('products/',include("products.urls",namespace="products")),
]

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, "homepage.html")

def welcome(request):
    return render(request, "welcome.html")

def lista(request):
    return render(request, "lista.html")

def chi_siamo(request):
    return render(request, "chi_siamo.html")

def variabili(request):
    context= {
        'var1': 'Prima variabile',
        'var2': 'Seconda variabile',
        'var3': 'Terza variabile',
    }
    return render(request, "variabili.html",context)

def index(request):
    return render(request, "index.html")

prima_app/templates/chi_siamo.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Chi Siamo {%endblock title%}

 {%block content%}
    <h1>Chi siamo</h1>
    <p>......</p>
 {%endblock content%}

prima_app/templates/homepage.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Homepage {%endblock title%}

 {%block content%}
    <h1>Homepage</h1>
    <p>Benvenuto</p>
 {%endblock content%}

prima_app/templates/index.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Index {%endblock title%}

 {%block content%}
    <ol>
        <li><a href="/">index root</a></li>
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
        <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
        <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
    </ol>
 {%endblock content%}

prima_app/templates/lista.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Lista {%endblock title%}

 {%block content%}
    <h1>Lista</h1>
    <ol>
        <li>Primo</li>
        <li>Secondo</li>
        <li>Terzo</li>
    </ol>
 {%endblock content%}

prima_app/templates/variabili.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Variabili {%endblock title%}

{%block content%}
    <h1>Variabili</h1>
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>

{%endblock content%}

prima_app/templates/welcome.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Variabili {%endblock title%}

 {%block content%}
    <h1>Welcome User</h1>
 {%endblock content%}