api/urls.py
from django.urls import path
from .views import todos_view, test_spotify

app_name = "api"
urlpatterns = [
    path('todos/', todos_view, name='todos'),
    path('spotify/', test_spotify, name='spotify')
]

eventi/urls.py
from django.urls import path
from .views import index, view_a, view_b, view_c, view_d

app_name = "eventi"

urlpatterns = [
    path('', index, name='index'),
    path('view_a', view_a, name='view_a'),
    path('view_b', view_b, name='view_b'),
    path('view_c', view_c, name='view_c'),
    path('view_d', view_d, name='view_d'),
]

forms_app/urls.py
from django.urls import path
from forms_app.views import contatti, lista_contatti, modifica_contatto, elimina_contatto

app_name = "forms_app"
urlpatterns = [
    path('contattacci/', contatti, name='contatti'),
    path('contatti/', lista_contatti, name='lista-contatti'),
    path('modifica_contatto/<int:pk>/', modifica_contatto, name='modifica-contatto'),
    path('elimina_contatto/<int:pk>/', elimina_contatto, name='elimina-contatto'),
]

news/urls.py
from django.urls import path
from .views import home, index, articoloDetailView, listaArticoli, queryBase, giornalistaDetailView

app_name = "news"

urlpatterns = [
    path('', index, name='index'),
    path('home', home, name='homeview'),
    path('articoli/<int:pk>', articoloDetailView, name='articolo_detail'),
    path('articoli', listaArticoli, name='lista_articoli'),
    path('giornalisti/<int:pk>', giornalistaDetailView, name='giornalista_detail'),
    #path('giornalisti', listaGiornalisti, name='lista_giornalisti'),
    path('query', queryBase, name='query_base')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root


app_name="primo_progetto"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('eventi/',include("eventi.urls",namespace="eventi")),
    path('rubrica/',include("rubrica.urls",namespace="rubrica")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('', index_root, name='index_root'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('api/',include("api.urls",namespace="api")),
    path('products/',include("products.urls",namespace="products")),
]

voti/urls.py
from django.urls import path
from voti.views import index,lista_materie, lista_voti, media_voti, max_min

app_name = "voti"
urlpatterns = [
    path('index', index, name='index'),
    path('lista_materie', lista_materie, name='lista_materie'),
    path('lista_voti', lista_voti, name='lista_voti'),
    path('media_voti', media_voti, name='media_voti'),
    path('max_min_voti', max_min, name='max_min_voti'),

]

templates/base.html
{% load static %}
<!doctype html> 
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'news.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index_root'%}">Primo Progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!--<li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>-->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Prima App
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Homepage</a>
                <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seconda App
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Es_if</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">If_else_elif</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Es_for</a>
                  
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  News
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'news:homeview'%}">Home news</a>
                  <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">Articoli</a>
                  <a class="dropdown-item" href="{% url 'news:query_base'%}">Query varie</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Voti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'voti:lista_materie'%}">Lista materie</a>
                  <a class="dropdown-item" href="{% url 'voti:lista_voti'%}">Voti studenti</a>
                  <a class="dropdown-item" href="{% url 'voti:media_voti'%}">Media studenti</a>
                  <a class="dropdown-item" href="{% url 'voti:max_min_voti'%}">Max Min voti</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Eventi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'eventi:view_a'%}">View_a</a>
                  <a class="dropdown-item" href="{% url 'eventi:view_b'%}">View_b</a>
                  <a class="dropdown-item" href="{% url 'eventi:view_c'%}">View_c</a>
                  <a class="dropdown-item" href="{% url 'eventi:view_d'%}">View_d</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Corsi di formazione
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'corsi_formazione:lista_corsi'%}">Lista corsi</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:lista_dettagli'%}">Lista dettagli</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_a'%}">View a</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_c'%}">View c</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_d'%}">View d</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_e'%}">View e</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:statistiche'%}">Statistiche</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Contatti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">Contattaci</a>
                  <a class="dropdown-item" href="{% url 'forms_app:lista-contatti'%}">Lista contatti</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  API
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'api:todos'%}">API todos</a>
                  <a class="dropdown-item" href="{% url 'api:spotify'%}">API spotify</a>
                </div>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <div class="dropdown-divider"></div>
                    <form id="logout-form" action="{% url 'logout' %}" method="post">
                      {% csrf_token %}
                      <button class="btn ft-power" type="submit">Logout</button>
                    </form>
                  </div>
                </li>
                <br>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}
          </ul>
        </div>
      </nav>
    <div class="container my-4">
        {%block content%}


        {%endblock content%}

        {%block script%}
        {%endblock script%}
    </div>
  </body>
</html>

templates/index_root.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Index2 {%endblock title%}

 {%block content%}
 <h1>PRIMO PROGETTO - ROOT MENU'</h1>
 <ol>
     <li><a href="/admin">Pannello admin</a></li>
     <li><a href="{% url 'prima_app:index'%}">Index prima app</a></li>
     <li><a href="{% url 'seconda_app:index'%}">Index seconda app</a></li>
     <li><a href="{% url 'news:index'%}">Index news</a></li>
     <li><a href="{% url 'voti:index'%}">Index voti</a></li>
     <li><a href="{% url 'eventi:index'%}">Index eventi</a></li>
     <li><a href="{% url 'corsi_formazione:index'%}">Index corsi</a></li>
     <li><a href="{% url 'forms_app:contatti'%}">Contattaci</a></li>
     <li><a href="{% url 'forms_app:lista-contatti'%}">Lista contatti</a></li>
     <li><a href="{% url 'api:todos'%}">API todos</a></li>
 </ol>
 {%endblock content%}