api/urls.py
from django.urls import path
from .views import todos_view, test_spotify

app_name = "api"
urlpatterns = [
    path('todos/', todos_view, name='todos'),
    path('spotify/', test_spotify, name='spotify')
]

news/urls.py
from django.urls import path
from .views import home, index, articoloDetailView, listaArticoli, queryBase, giornalistaDetailView

app_name = "news"

urlpatterns = [
    path('', index, name='index'),
    path('home', home, name='homeview'),
    path('articoli/<int:pk>', articoloDetailView, name='articolo_detail'),
    path('articoli', listaArticoli, name='lista_articoli'),
    path('giornalisti/<int:pk>', giornalistaDetailView, name='giornalista_detail'),
    #path('giornalisti', listaGiornalisti, name='lista_giornalisti'),
    path('query', queryBase, name='query_base')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root


app_name="primo_progetto"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('eventi/',include("eventi.urls",namespace="eventi")),
    path('rubrica/',include("rubrica.urls",namespace="rubrica")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('', index_root, name='index_root'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('api/',include("api.urls",namespace="api")),
    path('products/',include("products.urls",namespace="products")),
]

news/models.py
from django.db import models

class Giornalista(models.Model):
    """ il modello generico di un giornalista """
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)
    anno_di_nascita = models.DateField(blank=True)

    def __str__(self):
        return self.nome + " " + self.cognome
    
    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"
    
class Articolo(models.Model):
    """ il modello generico di un articolo """
    titolo = models.CharField(max_length=100) #limite di lunghezza per parametro
    contenuto = models.TextField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")
    data = models.DateField(auto_now=True, blank=True)
    visualizzazioni = models.IntegerField(default=0,blank=True)

    def __str__(self):
        return self.titolo
    
    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

news/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Articolo, Giornalista
import datetime

'''def home(request):
    a = ""
    g = ""

    for art in Articolo.objects.all():
        a += (art.titolo + "<br>")

    for gio in Giornalista.objects.all():
        g += (gio.nome + "<br>")
    response = "Articoli:<br>"+a+"<br>Giornalisti:<br>"+g

    return HttpResponse("<h1>"+response+"</h1>")'''

'''
def home(request):
    #al posto delle semplici stringhe si utilizzano gli array, più facili da gestire
    a = [] 
    g = []

    for art in Articolo.objects.all():
        a.append(art.titolo)

    for gio in Giornalista.objects.all():
        g.append(gio.nome)

    response = str(a) + "<br>" + str(g)
    print(response)

    return HttpResponse("<h1>"+response+"</h1>")
'''

def index(request):
    return render(request, "index_news.html")

def home(request):
    #al posto delle semplici stringhe si utilizzano gli array, più facili da gestire
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti": giornalisti}
    print(context)
    return render(request, "homepage_news.html", context)

def articoloDetailView(request, pk):
    articolo = get_object_or_404(Articolo, pk=pk)
    context = {"articolo": articolo}
    return render(request, "articolo_detail.html", context)

def giornalistaDetailView(request, pk):
    giornalista = get_object_or_404(Giornalista, pk=pk)
    #Inserire controllo per recuperare gli articoli del giornalista e passarlo nel context
    articoli_giornalista = giornalista.articoli.all()
    context = {
                "giornalista": giornalista,
                "articoli_giornalista": articoli_giornalista,
            }
    return render(request, "giornalista_detail.html", context)

def listaArticoli(request, pk=None):
    if pk == None:
        articoli=Articolo.objects.all()
    else:
        articoli=Articolo.objects.filter(giornalista_id=pk)
    context={
        'articoli':articoli,
    }
    return render(request,'lista_articoli.html',context)

def queryBase(request):
    #1. Tutti gli articoli scritti da giornalisti di un certo cognome
    articoli_cognome = Articolo.objects.filter(giornalista__cognome='Rossi')
    #2. Totale
    numero_totale_articoli = Articolo.objects.count()

    #3. Contare il numero di articoli scritti da un giornalista specifico:
    giornalista_2 = Giornalista.objects.get(id=2)
    numero_articoli_giornalista_1 = Articolo.objects.filter(giornalista=giornalista_2).count()

    #4. Ordinare gli articoli per numero di visualizzazioni in ordine decrescente:
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')

    #5. Tutti gli articoli che non hanno visualizzazioni:
    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni=0)

    #6. Articolo più visualizzato
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()

    #7. Tutti i giornalisti nati dopo una certa data:
    giornalisti_data = Giornalista.objects.filter(anno_di_nascita__gt=datetime.date(1990,1,1))

    #8. Tutti gli articoli pubblicati in una data specifica:
    articoli_del_giorno = Articolo.objects.filter(data=datetime.date(2023,1,1))

    #9. Tutti gli articoli pubblicati in un intervallo di date
    articoli_periodo = Articolo.objects.filter(data__range=(datetime.date(2023,1,1), datetime.date(2023,12,31)))

    #10. Gli articoli scritti da giornalisti nati prima del 1980
    giornalisti_nati = Giornalista.objects.filter(anno_di_nascita__lt=datetime.date(1980,1,1))
    articoli_giornalisti = Articolo.objects.filter(giornalista__in=giornalisti_nati)

    #11. Il giornalista più giovane:
    giornalista_giovane = Giornalista.objects.order_by('anno_di_nascita').first()

    #12. Il giornalista più anziano:
    giornalista_anziano = Giornalista.objects.order_by('-anno_di_nascita').first()

    #13. Gli ultimi 5 articoli pubblicati:
    ultimi = Articolo.objects.order_by('-data')[:5]

    #14. Tutti gli articoli con un certo numero minimo di visualizzazioni:
    articoli_minime_visualizzazioni = Articolo.objects.filter(visualizzazioni__gte=100)

    #15. Tutti gli articoli che contengono una certa parola nel titolo:
    articoli_parola = Articolo.objects.filter(titolo__icontains='importante')

    #16. Articoli pubblicati in un certo messe di un anno specifico:
    #nota per poter modificare la data di un articolo togliere la proprietà auto_now=True al field data nel model
    #poi dare i comandi makemigrations e migrate per applicare le modifiche al database
    articoli_mese_anno = Articolo.objects.filter(data__month=1, data__year=2023)

    #17. Giornalisti con almeno un articolo con più di 100 visualizzazioni
    giornalisti_con_articoli_popolari = Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct()

    """
    Giornalista.objects: inizia dalla classe del modello giornalista.
    .filter(articoli__visualizzazioni__gte=100): utilizza il metodo filter() per filtrare i giornalisti in
    base al campo visualizzazioni nel modello Articolo. La notazione articoli__visualizzazioni indica che si sta
    seguendo la relazione inversa dalla classe Giornalista alla classe ARticolo attraverso il campo ForeignKey giornalista
    nel modello Articolo.
    .distinct(): è  un metodo che assicura che i risultati siano distinti, eliminando eventuali duplicati.
    In questo caso, ciò è utile perchè un giornalista potrebbe essere associato a più articoli che soddisfano il criterio,
    e vogliamo ottenere solo una volta ogni giornalista che ha scritto almeno un articolo popolare.
    """

    #UTILIZZODI PIU CONDIZIONI DI SELEZIONE
    data = datetime.date(1990,1,1)
    visualizzazioni = 50
    #per mettere in AND le condizioni separarle con la virgola

    #18. Scrivi quali articoli vengano selezionati
    articoli_con_and = Articolo.objects.filter(giornalista__anno_di_nascita__gt=data, visualizzazioni__gte=visualizzazioni)

    #per mettere in OR le condizioni utilizzare l'operatore Q
    from django.db.models import Q
    #19. Scrivi quali articoli vengano selezionati
    articoli_con_or = Articolo.objects.filter(Q(giornalista__anno_di_nascita__gt=data) | Q(visualizzazioni__lte=visualizzazioni))

    #per il NOT utilizzare Q
    #20 Scrivi quali articoli vengano selezionati
    articoli_con_not = Articolo.objects.filter(~Q(giornalista__anno_di_nascita__lt=data))
    articoli_con_not = Articolo.objects.exclude(giornalista__anno_di_nascita__lt = data)


    #Creare il dizionario context
    context = {
        'articoli_cognome': articoli_cognome,
        'numero_totale_articoli': numero_totale_articoli,
        'numero_articoli_giornalista_1':numero_articoli_giornalista_1,
        'articoli_ordinati':articoli_ordinati,
        'articoli_senza_visualizzazioni':articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato':articolo_piu_visualizzato,
        'giornalisti_data':giornalisti_data,
        'articoli_del_giorno':articoli_del_giorno,
        'articoli_periodo':articoli_periodo,
        'articoli_giornalisti':articoli_giornalisti,
        'giornalista_giovane':giornalista_giovane,
        'giornalista_anziano':giornalista_anziano,
        'ultimi':ultimi,
        'articoli_minime_visualizzazioni':articoli_minime_visualizzazioni,
        'articoli_parola':articoli_parola,
        'articoli_mese_anno':articoli_mese_anno,
        'giornalisti_con_articoli_popolari':giornalisti_con_articoli_popolari,
        'articoli_con_and':articoli_con_and,
        'articoli_con_or':articoli_con_or,
        'articoli_con_not':articoli_con_not,
    }

    return render(request,'query.html',context)

news/templates/articolo_detail.html
{% extends "base.html"%}

{% block title %}
    {{ articolo.titolo }}
{% endblock title %}

{% block content %}
    <h1>{{ articolo.titolo }}</h1>
    <h3>{{ articolo.contenuto }}</h3>
    <h5>Autore: {{ articolo.giornalista }}</h5>
{% endblock content %}

news/templates/giornalista_detail.html
{% extends "base.html"%}

{% block title %}
    {{ giornalista.nome }} {{ giornalista.cognome }}
{% endblock title %}

{% block content %}

<p><strong>Nome: </strong> {{giornalista.nome}} </p>
<p><strong>Cognome: </strong> {{giornalista.cognome}} </p>
<p><strong>Anno di nascita: </strong> {{giornalista.anno_di_nascita}} </p>
<br>
<h5>I suoi articoli:</h5>
{% for articolo in articoli_giornalista%}
    <li><strong>Titolo: </strong><a href="/news/articoli/{{articolo.id}}"> {{articolo.titolo}} </a> - {{articolo.visualizzazioni}} visualizzazioni</li>
{% endfor %}

{% endblock content %}

news/templates/homepage_news.html
{% extends 'base.html'%}
{%block title%}
    Articoli e Giornalisti
{%endblock title%}
{%block content%} 
<h4>Articoli:</h4>
    {% for articolo in articoli %} 
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p> 
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        <hr> 
    {% endfor %} 
<h4>Giornalisti:</h4> 
    {% for giornalista in giornalisti %} 
        <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
        <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p> 
        <hr> 
    {% endfor %}
{%endblock content%}

news/templates/index_news.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Index news {%endblock title%}

 {%block content%}
    <ol>
        <li><a href="/">index root</a></li>
        <li><a href="{% url 'news:homeview'%}">Home news</a></li>
        <li><a href="{% url 'news:lista_articoli'%}">Articoli</a></li>
        <li><a href="{% url 'news:query_base'%}">Query varie</a></li>
    </ol>
 {%endblock content%}

news/templates/lista_articoli.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Lista articoli {%endblock title%}

{%block content%}
<h4>Lista articoli: </h4>

{% if articoli %}
    {% for articolo in articoli%}
        <p><strong>Titolo: </strong><a href="/news/articoli/{{articolo.id}}"> {{articolo.titolo}} </a></p>
        <p><strong>Contenuto: </strong> {{articolo.contenuto}}</p>
        <p><strong>Autore: </strong><a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{articolo.giornalista}}</a></p>
        <hr>
    {% endfor %}
{%endif%}

{%endblock content%}

news/templates/query.html
{% extends "base.html"%}
{%block title%} {{block.super}} | Query varie {%endblock title%}

 {%block content%}
    <h4>1. Tutti gli articoli scritti da giornalisti di un certo cognome</h4>
    <li>{{articoli_cognome}}</li>
    <hr>
    <h4>2. Numero totale di articoli</h4>
    <p>{{numero_totale_articoli}}</p>
    <hr>
    <h4>3. Numero di articoli scritti da un giornalista specifico</h4>
    <p>{{giornalista_1}}</p>
    <hr>
    <h4>4. Articoli ordinati per visualizzazioni</h4>
    <li>{{articoli_ordinati}}</li>
    <hr>
    <h4>5. Articoli senza visualizzazioni</h4>
    <li>{{articoli_senza_visualizzazioni}}</li>
    <hr>
    <h4>6. Articolo più visualizzato</h4>
    <p>{{articolo_piu_visualizzato}}</p>
    <hr>
    <h4>7. Giornalisti nati dopo il 1990</h4>
    <li>{{giornalisti_data}}</li>
    <hr>
    <h4>8. Articoli pubblicati il 1 gennaio 2023</h4>
    <li>{{articoli_del_giorno}}</li>
    <hr>
    <h4>9. Articoli pubblicati nel 2023</h4>
    <li>{{articoli_periodo}}</li>
    <hr>
    <h4>10. Articoli di giornalisti nati prima del 1980</h4>
    <li>{{articoli_giornalisti}}</li>
    <hr>
    <h4>11. Giornalista più giovane</h4>
    <p>{{giornalista_giovane}}</p>
    <hr>
    <h4>12. Giornalista più anziano</h4>
    <p>{{giornalista_anziano}}</p>
    <hr>
    <h4>13. Ultimi 5 articoli pubblicati</h4>
    <li>{{ultimi}}</li>
    <hr>
    <h4>14. Articoli con almeno 100 visualizzazioni</h4>
    <li>{{articoli_minime_visualizzazioni}}</li>
    <hr>
    <h4>15. Articoli con la parola "importante" nel titolo</h4>
    <li>{{articoli_parola}}</li>
    <hr>
    <h4>16. Articoli pubblicati in un determinato mese e anno</h4>
    <li>{{articoli_mese_anno}}</li>
    <hr>
    <h4>17. Giornalisti con articoli popolari</h4>
    <li>{{giornalisti_con_articoli_popolari}}</li>
    <hr>
    <h4>18. Articoli con AND</h4>
    <li>{{articoli_con_and}}</li>
    <hr>
    <h4>19. Articoli con OR</h4>
    <li>{{articoli_con_or}}</li>
    <hr>
    <h4>20. Articoli con NOT</h4>
    <li>{{articoli_con_not}}</li>
    <hr>

 {%endblock content%}